language: python

python:
    - 2.7
    - 3.4
    - 3.5

# Setting sudo to false opts in to Travis-CI container-based builds.
sudo: false

# The apt packages below are needed for sphinx builds. A full list of packages
# that can be included can be found here:
#
# https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-precise

addons:
    apt:
        packages:
            - graphviz
            - texlive-latex-extra
            - dvipng

env:
    global:
        - NUMPY_VERSION=stable
        - ASTROPY_VERSION=stable
        - SETUP_CMD='test'
        - PIP_DEPENDENCIES=''
        - CONDA_CHANNELS='astropy astropy-ci-extras'
        - CONDA_DEPENDENCIES='matplotlib mock h5py'

    matrix:
        - SETUP_CMD='egg_info'
        - SETUP_CMD='test'

matrix:
    include:

        # Try Astropy development and LTS versions
        - python: 2.7
          env: ASTROPY_VERSION=development
        - python: 3.5
          env: ASTROPY_VERSION=development
        - python: 2.7
          env: ASTROPY_VERSION=lts
        - python: 3.5
          env: ASTROPY_VERSION=lts

        # Try older numpy versions
        - python: 2.7
          env: NUMPY_VERSION=1.10
        - python: 2.7
          env: NUMPY_VERSION=1.9
        - python: 2.7
          env: NUMPY_VERSION=1.8
        - python: 2.7
          env: NUMPY_VERSION=1.7

        # Try numpy pre-release
        - python: 3.5
          env: NUMPY_VERSION=prerelease

install:

    # We now use the ci-helpers package to set up our testing environment.
    - git clone git://github.com/astropy/ci-helpers.git
    - source ci-helpers/travis/setup_conda_$TRAVIS_OS_NAME.sh

script:
   - python setup.py $SETUP_CMD
